"""Sync machine-verifiable facts into README.md generated regions.

Implements the terraform-docs marker pattern from the README-automation plan:
scripts own facts; humans own the prose around them. Only the region between
the BEGIN/END markers is ever rewritten.

    <!-- BEGIN GENERATED: repo-facts -->
    ...regenerated content...
    <!-- END GENERATED: repo-facts -->

Run:  uv run python scripts/readme_sync.py build   # rewrite the region
      uv run python scripts/readme_sync.py check   # exit 1 if stale (CI)

Test count requires the submodule (tests import game.state); when collection
fails the fact is reported honestly as "n/a (submodule not initialized)".
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
README = ROOT / "README.md"
BEGIN = "<!-- BEGIN GENERATED: repo-facts -->"
END = "<!-- END GENERATED: repo-facts -->"


def _test_count() -> str:
    """Count collected tests; degrade honestly if the submodule is absent."""
    try:
        out = subprocess.run(
            ["uv", "run", "pytest", "--collect-only", "-q"],
            capture_output=True, text=True, cwd=ROOT, timeout=120,
        )
    except (OSError, subprocess.TimeoutExpired):
        return "n/a (pytest unavailable)"
    if out.returncode != 0:
        return "n/a (submodule not initialized)"
    for line in reversed(out.stdout.splitlines()):
        if "test" in line and ("collected" in line or "selected" in line):
            return line.strip()
    return "n/a"


def _module_table() -> str:
    """Line-count inventory of src/actor_brains modules (150-line rule evidence)."""
    rows = ["| Module | Lines |", "|--------|-------|"]
    for p in sorted((ROOT / "src" / "actor_brains").rglob("*.py")):
        n = len(p.read_text(encoding="utf-8").splitlines())
        rows.append(f"| `{p.relative_to(ROOT / 'src')}` | {n} |")
    return "\n".join(rows)


def _model_facts() -> str:
    rows = []
    for name in ("cop_qtable.npy", "thief_qtable.npy"):
        p = ROOT / "models" / name
        rows.append(
            f"- `models/{name}`: {p.stat().st_size:,} bytes"
            if p.exists() else f"- `models/{name}`: MISSING"
        )
    return "\n".join(rows)


def _render() -> str:
    return (
        f"{BEGIN}\n"
        f"_Facts below are generated by `scripts/readme_sync.py` — do not edit._\n\n"
        f"**Tests:** {_test_count()}\n\n"
        f"**Modules (150-line rule):**\n\n{_module_table()}\n\n"
        f"**Trained models:**\n{_model_facts()}\n"
        f"{END}"
    )


def _inject(text: str, block: str) -> str:
    start = text.find(BEGIN)
    end = text.find(END)
    if start == -1 or end == -1:
        raise SystemExit(
            f"README.md is missing the markers:\n  {BEGIN}\n  {END}\n"
            "Add them once where the facts block should live."
        )
    return text[:start] + block + text[end + len(END):]


def main() -> int:
    """Build or check the generated repo-facts region in README.md."""
    mode = sys.argv[1] if len(sys.argv) > 1 else "build"
    current = README.read_text(encoding="utf-8")
    updated = _inject(current, _render())
    if mode == "check":
        if current != updated:
            print("STALE: README repo-facts region is out of date. "
                  "Run: uv run python scripts/readme_sync.py build")
            return 1
        print("OK: README repo-facts region is up to date")
        return 0
    README.write_text(updated, encoding="utf-8")
    print("README repo-facts region rewritten")
    return 0


if __name__ == "__main__":
    sys.exit(main())
